name: council_of_state
description: A flutter login model app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  cupertino_icons: ^1.0.5
  dio: ^5.3.0
  fl_chart: ^0.63.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  flutter_launcher_icons: ^0.13.1
  dashboard: ^0.0.3+1
  intl: ^0.18.0
  badges: ^3.1.1
  awesome_dialog: ^3.1.0
  internet_connection_checker: ^1.0.0+1
  flutter_native_splash: ^2.3.5
  jiffy: ^5.0.1
  flutter_localization: ^0.1.14


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.PNG
    - assets/images/error.png
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/static/Cairo-ExtraLight.ttf
        - asset: assets/fonts/static/Cairo-Light.ttf
        - asset: assets/fonts/static/Cairo-Regular.ttf
        - asset: assets/fonts/static/Cairo-Medium.ttf
        - asset: assets/fonts/static/Cairo-SemiBold.ttf
        - asset: assets/fonts/static/Cairo-Bold.ttf
        - asset: assets/fonts/static/Cairo-ExtraBold.ttf
        - asset: assets/fonts/static/Cairo-Black.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.PNG"
  min_sdk_android: 21 
  color: "#d5aa6d"
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#d5aa6d"
  image: assets/images/logo.PNG
  ios: true
  android_gravity: center
